#!/bin/sh
#
# 1 ./manage_externals/get_rtma
# 2 ./devbuild.sh
# 3 source env/wflow_jet.env (use other wflow files for different platforms)
#   cd regional_workflow/ush
#   cp config.sh.RTMA_NA_3km config.sh
#   vi config.sh (modify EXPT_BASEDIR, STMP, PTMP and other variables accordingly)
# 4 ./generate_FV3LAM_wflow.sh
#
basedir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
${basedir}/checkout_externals --externals ${basedir}/../Externals.rtma
