# This workflow Builds the UFS SRWEATHER APP
name: Build SRWA

on:
  push:
    branches: [ rrfs_ci, feature/CI_build_test ]
  pull_request:
    branches: [ rrfs_ci ]

# Use a default login shell which loads intel/oneapi/setvars.sh, and lmod path 
defaults:
  run:
    shell: bash -l {0}

jobs:

  Clone_SRWA:
    name: Clone Repo
    runs-on: self-hosted 
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: feature/CI_build_test
  
  Configure_SRWA:
    name: Update Scripts 
    runs-on: self-hosted 
    needs: [ Clone_SRWA ]
    
    steps:
      - name: Update scripts 
        run: |
          sed -i "99i  \  `hostname -f`)     MACHINE_ID=aws ;;   ### pcluster" env/detect_machine.sh
  
  Build_SRWA:
    name: Build SRWA 
    runs-on: self-hosted
    needs: [ Clone_SRWA, Configure_SRWA ]
    
    steps:
      - name: Build Short Range Weather App using test/build.sh
        run: |
          ./manage_externals/checkout_externals
          cd test/
          ./build.sh >& build_test.out
          cat build_test*
